name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # CACHE NODE_MODULES
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # INSTALL DEPENDENCIES
      - name: Install dependencies
        run: npm ci

      # CACHE PLAYWRIGHT BROWSERS
      - uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright

      # INSTALL PLAYWRIGHT BROWSERS
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # RUN TESTS
      - name: Run Playwright tests
        run: npx playwright test --workers=3   # change workers as needed

      # UPLOAD REPORT
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
       # New: Upload diffs if screenshots mismatch
      - name: Upload screenshot diffs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-diffs
          path: |
            **/*.diff.png
            **/*.actual.png
